# Generated by Django 4.2.16 on 2026-04-14 05:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('project', '__first__'),
        ('master_data', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanTask',
            fields=[
                ('plan_task_id', models.AutoField(primary_key=True, serialize=False, verbose_name='任务ID')),
                ('task_name', models.CharField(max_length=200, verbose_name='任务名称')),
                ('task_level', models.IntegerField(default=1, verbose_name='任务层级')),
                ('pre_task_code', models.CharField(blank=True, max_length=50, verbose_name='前置任务编码')),
                ('logic_relation', models.CharField(choices=[('FS', '完成-开始'), ('SF', '开始-完成'), ('FF', '完成-完成'), ('SS', '开始-开始')], default='FS', max_length=10, verbose_name='逻辑关系')),
                ('department', models.CharField(blank=True, max_length=100, verbose_name='部门')),
                ('task_owner', models.CharField(blank=True, max_length=100, verbose_name='任务负责人')),
                ('authorized_owner', models.CharField(blank=True, max_length=100, verbose_name='授权负责人')),
                ('planned_start_date', models.DateField(blank=True, null=True, verbose_name='计划开始日期')),
                ('planned_end_date', models.DateField(blank=True, null=True, verbose_name='计划结束日期')),
                ('workload_days', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='工作量（天）')),
                ('task_status', models.CharField(choices=[('NOT_STARTED', '未开始'), ('IN_PROGRESS', '进行中'), ('COMPLETED', '已完成'), ('SUSPENDED', '已暂停'), ('CANCELLED', '已取消'), ('DELAYED', '已延期'), ('PENDING_REVIEW', '待审核'), ('APPROVED', '已审批'), ('REJECTED', '已驳回')], default='NOT_STARTED', max_length=20, verbose_name='任务状态')),
                ('has_deliverable', models.CharField(default='N', max_length=1, verbose_name='是否有交付物')),
                ('is_hour_task', models.CharField(default='N', max_length=1, verbose_name='是否工时任务')),
                ('acceptance_item', models.CharField(blank=True, max_length=500, verbose_name='验收项')),
                ('remark', models.TextField(blank=True, verbose_name='备注')),
                ('phase', models.CharField(blank=True, max_length=50, verbose_name='阶段')),
                ('progress_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='完成百分比')),
                ('include_weekend', models.CharField(default='N', max_length=1, verbose_name='包含周末')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序序号')),
                ('created_by', models.CharField(max_length=100, verbose_name='创建人')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('parent_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='plan.plantask', verbose_name='父任务')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_tasks', to='project.project', verbose_name='所属项目')),
            ],
            options={
                'verbose_name': '计划任务',
                'verbose_name_plural': '计划任务',
                'db_table': 'hpm_plan_task',
                'ordering': ['sort_order', 'plan_task_id'],
            },
        ),
        migrations.CreateModel(
            name='ResourceReserve',
            fields=[
                ('reserve_id', models.AutoField(primary_key=True, serialize=False, verbose_name='预占ID')),
                ('project_short_code', models.CharField(max_length=50, verbose_name='项目简码')),
                ('resource_type', models.CharField(choices=[('BENCH', '台位'), ('PERSON', '人员'), ('EQUIPMENT', '设备')], max_length=50, verbose_name='资源类型')),
                ('resource_code', models.CharField(max_length=50, verbose_name='资源编码')),
                ('resource_name', models.CharField(blank=True, max_length=200, verbose_name='资源名称')),
                ('reserve_start_time', models.DateTimeField(verbose_name='预占开始时间')),
                ('reserve_end_time', models.DateTimeField(verbose_name='预占结束时间')),
                ('reserve_status', models.CharField(choices=[('RESERVED', '已预占'), ('RELEASED', '已释放'), ('USED', '已使用')], default='RESERVED', max_length=20, verbose_name='预占状态')),
                ('created_by', models.CharField(max_length=100, verbose_name='创建人')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resource_reserves', to='project.project', verbose_name='所属项目')),
            ],
            options={
                'verbose_name': '资源预占',
                'verbose_name_plural': '资源预占',
                'db_table': 'hpm_resource_reserve',
            },
        ),
        migrations.CreateModel(
            name='ResourcePlan',
            fields=[
                ('resource_plan_id', models.AutoField(primary_key=True, serialize=False, verbose_name='资源计划ID')),
                ('resource_type', models.CharField(choices=[('PERSON', '人员'), ('EQUIPMENT', '设备'), ('BENCH', '台位')], max_length=50, verbose_name='资源类型')),
                ('resource_code', models.CharField(max_length=50, verbose_name='资源编码')),
                ('resource_name', models.CharField(blank=True, max_length=200, verbose_name='资源名称')),
                ('resource_quantity', models.IntegerField(default=1, verbose_name='资源数量')),
                ('daily_effective_hours', models.DecimalField(decimal_places=2, default=8, max_digits=5, verbose_name='日有效工时（小时）')),
                ('resource_price', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='资源单价')),
                ('price_unit', models.CharField(default='HOUR', max_length=20, verbose_name='计价单位')),
                ('planned_start_date', models.DateField(blank=True, null=True, verbose_name='计划开始日期')),
                ('planned_end_date', models.DateField(blank=True, null=True, verbose_name='计划结束日期')),
                ('include_weekend', models.CharField(default='N', max_length=1, verbose_name='包含周末')),
                ('resource_manager', models.CharField(blank=True, max_length=100, verbose_name='资源管理人')),
                ('remark', models.TextField(blank=True, verbose_name='备注')),
                ('status', models.CharField(choices=[('ACTIVE', '有效'), ('INACTIVE', '无效')], default='ACTIVE', max_length=20, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('price_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resource_plans', to='master_data.priceheader', verbose_name='价格版本')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resource_plans', to='project.project', verbose_name='所属项目')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resource_plans', to='plan.plantask', verbose_name='关联任务')),
            ],
            options={
                'verbose_name': '资源计划',
                'verbose_name_plural': '资源计划',
                'db_table': 'hpm_resource_plan',
            },
        ),
        migrations.CreateModel(
            name='PlanVersion',
            fields=[
                ('version_id', models.AutoField(primary_key=True, serialize=False, verbose_name='版本ID')),
                ('version_no', models.CharField(max_length=20, verbose_name='版本号')),
                ('version_name', models.CharField(blank=True, max_length=100, verbose_name='版本名称')),
                ('status', models.CharField(choices=[('DRAFT', '草稿'), ('PUBLISHED', '已发布'), ('ARCHIVED', '已归档')], default='DRAFT', max_length=20, verbose_name='状态')),
                ('is_current', models.BooleanField(default=False, verbose_name='是否当前版本')),
                ('publish_date', models.DateField(blank=True, null=True, verbose_name='发布日期')),
                ('published_by', models.CharField(blank=True, max_length=100, verbose_name='发布人')),
                ('remark', models.TextField(blank=True, verbose_name='备注')),
                ('created_by', models.CharField(max_length=100, verbose_name='创建人')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_versions', to='project.project', verbose_name='所属项目')),
            ],
            options={
                'verbose_name': '计划版本',
                'verbose_name_plural': '计划版本',
                'db_table': 'hpm_plan_version',
                'unique_together': {('project', 'version_no')},
            },
        ),
        migrations.AddField(
            model_name='plantask',
            name='version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='plan.planversion', verbose_name='计划版本'),
        ),
    ]
