# Generated by Django 4.2.16 on 2026-04-21 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0002_plantaskdependency'),
    ]

    operations = [
        migrations.AddField(
            model_name='plantask',
            name='baseline_end_date',
            field=models.DateField(blank=True, null=True, verbose_name='基线结束日期'),
        ),
        migrations.AddField(
            model_name='plantask',
            name='baseline_start_date',
            field=models.DateField(blank=True, null=True, verbose_name='基线开始日期'),
        ),
    ]
